# gem 'pg'

default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  host: localhost
  port: 5432
  pool: 5
  username: deploy
  password: deploy_password

development:
  <<: *default
  database: truckbu_development

production:
  <<: *default
  database: deploy_production
